Post/feed component
Billennium-frontend-interns/linkedin_clone_project pull request #25
Opened 2021-07-27 12:20 UTC by jakub-gosciniak

# Related issue
- Post feed comonent to display user posts

# Changes
- Added FeedPost component
- Added moment package
- Added routing to user
- Added custom hook for content overflowing at window resizing
- Changed export default in firebase to export

# Additional information
- Add any additional information or context

# Checklist
- [x] Performed self-review
- [ ] Added data-testId for UI elements
- [ ] Tests
- [x] Storybook

# Screenshots
- The horizontal margins are added by storybook by default, the component itself spans from left to right on mobile devices.
![image](https://user-images.githubusercontent.com/87001663/127151512-135517ae-9699-4d89-9821-8527cd5b41ac.png)
![image](https://user-images.githubusercontent.com/87001663/127151825-953ed4aa-cf8e-4a55-bfb1-148c716f1f2c.png)
![image](https://user-images.githubusercontent.com/87001663/127151874-05eabf71-06ed-4f33-9e58-8549a48fc147.png)

2021-07-27 13:05 UTC, Polo11121 commented on src/components/FeedPost/FeedPost.scss
> +    background: white;
all colors should be in Colors.scss !

2021-07-27 13:05 UTC, Polo11121 commented on src/components/FeedPost/FeedPost.scss
> +    color: black;
Colors.scss : )

2021-07-27 13:09 UTC, Polo11121 submitted a review, later dismissed
Looks clean, just remember that all colors should be in Colors.scss : )

2021-07-27 17:48 UTC, MateuszLisowski commented on src/styles/Colors.scss
> +$postTextBlack:black;
```suggestion
$postTextBlack: black;
```

2021-07-27 17:50 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.scss
> +.feedPost__container{
look at other files and components. There is always one root clas like "feedPost" and below there is somethig like this

```
.feedPost {
&__container {
...
}
&__user {
..
}
}
```

It should be definitely refactored

2021-07-27 20:46 UTC, mateusz0612 commented on src/components/FeedPost/FeedPost.tsx
> +    <article className="feedPost__container">
In my opinion it should be 'feedPost'

2021-07-28 07:05 UTC, MatYouKy requested changes
Please see the comments and make changes accordingly.

2021-07-28 07:34 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.scss
> +  &__container {
I think it's not necessarry

2021-07-28 07:43 UTC, MateuszLisowski commented on src/styles/Colors.scss
> +$postTextBlack: black;
```suggestion
$black: black;
```

2021-07-28 07:44 UTC, MateuszLisowski commented on src/styles/Colors.scss
> +$postBackgroundWhite: white;
```suggestion
$white: white;
```

2021-07-28 07:44 UTC, MateuszLisowski commented on src/stories/FeedPost/FeedPost.stories.tsx
> +const text = 'Social media bez memów? Ale jak to???';
add enter for better readability

2021-07-28 07:45 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.tsx
> +    <article className="feedPost__container">
Agree, feedPost is missing here

2021-07-28 07:47 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.scss
> +    background: white;
use $white

2021-07-28 07:47 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.scss
> +    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
you could add it to Fonts

2021-07-28 07:48 UTC, MateuszLisowski commented on src/actions/useIsContentOverflowing.tsx
> +    function handleResize() {
you could use arrow function here

2021-07-28 07:52 UTC, MatYouKy approved these changes

2021-07-28 07:52 UTC, MateuszLisowski commented on src/components/FeedPost/FeedPost.scss
> +    @media only screen and (max-width: $mobile) {
I don't agree

2021-07-28 08:11 UTC, mateusz0612 commented on src/components/FeedPost/FeedPost.tsx
> +  uid: string;
I think it should be ownerUid like in firebase collection.

2021-07-28 09:05 UTC, mateusz0612 approved these changes
It looks good. Very nice that you added default image.

2021-07-28 09:07 UTC, MatYouKy approved these changes

2021-07-28 09:07 UTC, MateuszLisowski commented on src/styles/Fonts.scss
> +$postText:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
I think we should reuse fonts so the name should be more general (not specifici lie postText

2021-07-28 09:07 UTC, MateuszLisowski approved these changes

2021-07-28 09:25 UTC, Polo11121 approved these changes
OK

2021-07-28 09:45 UTC, merged