Add expand button in recommended users section
Billennium-frontend-interns/linkedin_clone_project pull request #37
Opened 2021-08-06 07:09 UTC by Polo11121

# Related issue
- [NETWORK] Follow User (recommended users section)

# Changes
- More recommended users can now be displayed, and you don't have to switch from one tab to another now to change them.

# Additional information
- Small feature.

# Checklist
- [ ] Performed self-review
- [ ] Added data-testId for UI elements
- [ ] Tests
- [ ] Storybook

# Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/87152087/128470779-cac3d405-8ab5-4fcc-8b52-4a236bfd1b5d.png)

2021-08-06 07:10 UTC, jakub-gosciniak approved these changes

2021-08-06 08:32 UTC, MateuszLisowski commented on src/components/RecommendedUsers/RecommendedUsers.tsx
> +          <IconButton onClick={() => setRecommendedUsers(recommendedUsers?.concat(getRecommendedUsersInfo()))}>
you could use spread operator

2021-08-06 08:32 UTC, MateuszLisowski requested changes
Left one comment :)

2021-08-06 09:04 UTC, MatYouKy submitted a review, later dismissed

2021-08-06 12:49 UTC, jakub-gosciniak submitted a review, later dismissed

2021-08-06 16:17 UTC, MateuszLisowski approved these changes

2021-08-06 21:30 UTC, mateusz0612 approved these changes

2021-08-09 06:52 UTC, MateuszLisowski approved these changes

2021-08-09 06:53 UTC, mateusz0612 approved these changes

2021-08-09 06:53 UTC, jakub-gosciniak approved these changes

2021-08-09 06:53 UTC, MatYouKy approved these changes

2021-08-09 06:53 UTC, merged